name: Package
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      packageName:
        type: string
        default: package
      bazelBuildArgs:
        type: string
        default: '--experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0'
      windowsBuildArgs:
        type: string
        default: '--desktop cpu --opencv cmake'

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs for debug
        run: |
          echo 'inputs.ref=${{ inputs.ref }}'
          echo 'inputs.windowsBuildArgs=${{ inputs.windowsBuildArgs }}' 

  windows-build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Build a Docker image
        run: |
          docker build --no-cache -t mediapipe_unity:latest . -f docker/windows/x86_64/Dockerfile
        shell: cmd
        timeout-minutes: 60

      - name: Build
        run: |
          docker run --rm --cpus=2 --memory=8g ^
            --mount type=bind,src=%CD%\Packages,dst=C:\mediapipe\Packages ^
            mediapipe_unity:latest ^
            python build.py build --bazel_build_opts="${{ inputs.bazelBuildArgs }}" ${{ inputs.windowsBuildArgs }} -vv
        shell: cmd
        
      - name: Upload mediapipe_c.dll
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.packageName }}-mediapipe_c.dll
          path: Packages/com.github.homuler.mediapipe/Runtime/Plugins/mediapipe_c.dll
          
      - name: build dotnet package
        run: |
          dir
          cd Mediapipe.Net.Runtime.CPU          
          mkdir runtimes\win-x64\native
          copy ..\Packages\com.github.homuler.mediapipe\Runtime\Plugins\mediapipe_c.dll .\runtimes\win-x64\native\
          dotnet build
          ## OLD KAYMYST NUGET PUSH ## dotnet nuget push .\bin\Debug\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_TOKEN}} --skip-duplicate
          nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -Username "${{ github.actor }}" -Password "${{ secrets.GITHUB_TOKEN }}"
          nuget push .\bin\Debug\*.nupkg -Source "GitHub"
        shell: cmd

  package:
    runs-on: ubuntu-latest
    needs:
      - windows-build
    steps:
      
      - name: Download mediapipe_c.dll
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.packageName }}-mediapipe_c.dll
          path: Packages/com.github.homuler.mediapipe/Runtime/Plugins

      - name: Zip all
        run: |
          zip -r MediaPipeUnityPlugin-all.zip . -x .git/**\*

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.packageName }}
          path: |
            MediaPipeUnityPlugin-all.zip
          retention-days: 7

  clean:
    runs-on: ubuntu-latest
    needs:
      - package
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ inputs.packageName }}-base
          failOnError: false

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ inputs.packageName }}-mediapipe_c.dll
          failOnError: false
